default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      timeout: 5000
      username: d3v17
      password: password

development:
  <<: *default
  database: postapp_development

test:
  <<: *default
  database: postapp_test

production:
  <<: *default
  database: postapp_production

